<?php

//VidioCast Constant Variables
define('LOG_OUT', __('Logout', 'videocraft'));
define('ADD_LISTING', __('Add Video', 'videocraft'));
define('REG', __('Register', 'videocraft'));
define('LOG_REG', __('Login/Register', 'videocraft'));
define('SIGN', __('Sign In', 'videocraft'));
define('A_MSG_ST_EMAIL', __('A message will be sent to your email address.', 'videocraft'));
define('UR_CMT_AWAIT', __('Your comment is awaiting moderation.', 'videocraft'));
define('EDIT_PROFILE', __('Edit profile', 'videocraft'));
define('FREE', __('Create a free account', 'videocraft'));
define('U_NAME', __('User Name:', 'videocraft'));
define('EMAIL', __('Email:', 'videocraft'));
define('PASS', __('Enter a Password:', 'videocraft'));
define('AGAIN_PASS', __('Enter Password again:', 'videocraft'));
define('LOST_D', __('if you lost your password then click on the link shown below', 'videocraft'));
define('LOST', __('Lost your password?', 'videocraft'));
define('FORGOT', __('Forget Your PassWord?', 'videocraft'));
define('NEW_EMAIL', __('Enter your new email or username:', 'videocraft'));
define('SLT_ALL', __('Select All', 'videocraft'));
define('ACTION', __('Action', 'videocraft'));
define('DUMMY_DT_DLT', __('All Dummy data has been removed from your database successfully!', 'videocraft'));
define('THEME_ACTIVATED', __('Theme activated successfully.', 'videocraft'));
define('SAMPLE_DT_PAPU', __('Sample data has been populated on your site. Wish to delete sample data?', 'videocraft'));
define('YES_DEL', __('Yes Delete Please!', 'videocraft'));
define('LIKE_TOP_POPULATED', __('Would you like to populate sample data on your site?', 'videocraft'));
define('MEMBER_SINCE', __('Member Since', 'videocraft'));
define('ADD_N_LISTING', __('Add New Video', 'videocraft'));
define('V_LISTING', __('View All', 'videocraft'));
define('PAGE_NAVIGATION', __('Pages Navigation Menu', 'videocraft'));
define('RETURN_TO', __('Return to %s', 'videocraft'));
define('BY_AUTHOR', __('By %2$s', 'videocraft'));
define('VIEW_ALL_POST_BY', __('View all posts by %s', 'videocraft'));
define('PUBLISHED_DATE', __('Published %2$s', 'videocraft'));
define('FULL_SIZE_IS_PIXEL', __('Full size is %s pixels', 'videocraft'));
define('LINK_TO_FULL_SIZE_IMAGE', __('Link to full-size image', 'videocraft'));
define('EDIT', __('Edit', 'videocraft'));
define('DELETE', __('Delete', 'videocraft'));
define('VIEW', __('View', 'videocraft'));
define('ITEMS', __('Item', 'videocraft'));
define('CONTINUE_READING', __('Continue reading &rarr;', 'videocraft'));
define('PAGES_COLON', __('Pages:', 'videocraft'));
define('AUTHOR_ARCHIVES', __('Author Archives: %s', 'videocraft'));
define('ABOUT', __('About %s', 'videocraft'));
define('OLER_POST', __('&larr; Older posts', 'videocraft'));
define('NEWER_POST', __('Newer posts &rarr;', 'videocraft'));
define('DAILY_ARCHIVES', __('Daily Archives: %s', 'videocraft'));
define('MONTHLY_ARCHIVES', __('Monthly Archives: %s', 'videocraft'));
define('YEARLY_ARCHIVES', __('Yearly Archives: %s', 'videocraft'));
define('BLOG_ARCHIVES', __('Blog Archives', 'videocraft'));
define('CATEGORY_ARCHIVES', __('Category Archives: %s', 'videocraft'));
define('MAIL_MENU', __('Main Menu', 'videocraft'));
define('HOME', __('Home', 'videocraft'));
define('PAGE', __('Page', 'videocraft'));
define('THIS_ENTRY_WAS_POSTED_IN', __('This entry was posted in %1$s', 'videocraft'));
define('BOOKMARK_THE', __('Bookmark the', 'videocraft'));
define('PERMALINK', __('permalink', 'videocraft'));
define('PRIMARY_WIDGET_AREA', __('Primary Widget Area', 'videocraft'));
define('SECONDARY_WIDGET_AREA', __('Secondary Widget Area', 'videocraft'));
define('HOME_PAGE_SIDEBAR_WIDGET_AREA', __('Home Page Sidebar Widget Area', 'videocraft'));
define('FIRST_FOOTER_WIDGETS_AREA', __('First Footer Widget Area', 'videocraft'));
define('SECONG_FOOTER_WIDGET_AREA', __('Second Footer Widget Area', 'videocraft'));
define('THIRD_FOOTER_WIDGET_AREA', __('Third Footer Widget Area', 'videocraft'));
define('FOURTH_FOOTER_WIDGET_AREA', __('Fourth Footer Widget Area', 'videocraft'));
define('POST_TAGGED_WITH', __('Post Tagged with', 'videocraft'));
define('PREVIOUS_POST', __('Previous Post', 'videocraft'));
define('NEXT_POST', __('Next Post', 'videocraft'));
define('TRY_LOOKING_IN_MONTHLY_ARCHIVES', __('Try looking in the monthly archives. %1$s', 'videocraft'));
define('INSTALL_REQUIRED_PLUGIN', __('Install Required Plugins', 'videocraft'));
define('SEARCH_RESULTS_FOR', __('Search Results for: %s', 'videocraft'));
define('NOTHING_FOUND', __('Nothing Found', 'videocraft'));
define('SORRY_NOTHING_FOUND_TRY_AGAIN', __('Sorry, but nothing matched your search criteria. Please try again with some different keywords.', 'videocraft'));
define('TAG_ARCHIVES', __('Tag Archives: %s', 'videocraft'));
define('CATEGORIES', __('Categories', 'videocraft'));
define('ARCHIVES', __('Archives', 'videocraft'));
define('CAPTCHA_FIELD', __('Captcha Field', 'videocraft'));
define('THIS_IS_EMBRASSING', __('This is somewhat embarrassing, isn&rsquo;t it?', 'videocraft'));
define('READ_MORE', __('Read More', 'videocraft'));
define('CONTACT_NAME', __('Name', 'videocraft'));
define('CONTACT_EMAIL', __('E-mail', 'videocraft'));
define('CONTACT_MESSAGE', __('Message', 'videocraft'));
define('CONTACT_SUBMIT', __('Submit', 'videocraft'));
define('NO_RSPNS', __('No Responses', 'videocraft'));
define('ONE_RSPNS', __('One Responses', 'videocraft'));
define('RSPNS', __('% Responses', 'videocraft'));
define('LV_CMT', __('Leave a Comment', 'videocraft'));
define('CMNT_CLSD', __('Comments are closed.', 'videocraft'));
define('NO_CMNT', __('No Comments', 'videocraft'));
define('ONE_CMNT', __('1 Comments', 'videocraft'));
define('CMNT', __('% Comments', 'videocraft'));
define('CMNT_OFF', __('Comments off', 'videocraft'));
define('FORM_SEARCH', __('Search', 'videocraft'));
define('TEMPLATEURL', get_template_directory_uri());
?>